# Edwards & Gray Estate Agent AI Chatbot
[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "zisi"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://generativelanguage.googleapis.com https://images.unsplash.com;"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
